#pragma once

#include <SFML/Graphics.hpp>


const unsigned int WINDOW_MANAGER_WIDTH = 869,
WINDOW_MANAGER_HEIGHT = 867;

const sf::Vector2f MENU_BUTTON_DEFA_SIZE = { 0.33f, 0.33f },
PLAY_BTN_POS = { WINDOW_MANAGER_WIDTH / 2 - MENU_BUTTON_DEFA_SIZE.x / 2,
					WINDOW_MANAGER_HEIGHT / 2 - 200 },
	LOAD_BTN_POS = { WINDOW_MANAGER_WIDTH / 2 - MENU_BUTTON_DEFA_SIZE.x / 2,
						WINDOW_MANAGER_HEIGHT / 2 },
	EXIT_BTN_POS = { WINDOW_MANAGER_WIDTH / 2 - MENU_BUTTON_DEFA_SIZE.x / 2,
							WINDOW_MANAGER_HEIGHT / 2 + 200 };